name: Deploy to GCS
description: Deploy to GCS bucket
inputs:
  bucket:
    description: Name of the bucket to deploy
    required: true
  path:
    description: Path of the artifacts to deploy
    required: false
    default: dist
  workload_identity_provider:
    description: The workload identity provider to use
    required: true

runs:
  using: composite
  steps:
    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}

    - run: gsutil -m -h "Cache-Control:no-store" rsync -dr ${{ inputs.path }} ${{ inputs.bucket }}
      shell: bash
