name: Deploy to GCS
description: Deploy to GCS bucket
inputs:
  bucket:
    description: Name of the bucket to deploy
    required: true
  path:
    description: Path of the artifacts to deploy
    required: false
    default: dist

runs:
  using: composite
  steps:
    - run: gsutil -m -h "Cache-Control:no-store" rsync -dr ${{ inputs.path }} ${{ inputs.bucket }}
      shell: bash
