name: ⭐️ Deploy development
on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-dev]

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.check.outputs.deploy }}
    environment: dev
    steps:
      - name: Check if deploy is needed
        id: check
        run: |
          if [ -n "${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}" ]; then
            echo "deploy=true" >> $GITHUB_OUTPUT
          end

  deploy_ar:
    runs-on: ubuntu-latest
    environment: dev
    needs: check
    if: ${{ needs.check.outputs.deploy == 'true' }}
    permissions:
      contents: read  # To checkout
      id-token: write # To authenticate with GCP using OIDC
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          branch: main
          workflow: ci.yml
          name: ar
          path: dist
          check_artifacts: true
          search_artifacts: true

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: google-github-actions/setup-gcloud@v2

      - run: gsutil -m -h "Cache-Control:no-store" rsync -dr dist gs://${{ vars.GCS_DEST }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ar
          path: dist/**/*
