name: ⭐️ Deploy production
on:
  workflow_dispatch:
jobs:
  deploy_ar:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW-3.0'
    environment: prod
    defaults:
      run:
        working-directory: ar
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Download web artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          branch: main
          workflow: deploy-ar-dev.yml
          name: ar
          path: ar/dist
          check_artifacts: true
          search_artifacts: true
      - name: Deploy
        run: gsutil -m -h "Cache-Control:no-store" rsync -dr dist ${{ vars.GCS_DEST }}
