name: ⭐️ Deploy production
on:
  workflow_dispatch:
jobs:
  deploy_ar:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW-3.0'
    environment: prod
    defaults:
      run:
        working-directory: ar
    steps:
      - uses: actions/checkout@v4

      - name: Download web artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          branch: main
          workflow: deploy-dev.yml
          name: ar
          path: dist
          check_artifacts: true
          search_artifacts: true

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Deploy
        uses: ./.github/actions/deploy-to-gcs
        with:
          bucket: ${{ vars.GCS_DEST }}
